---
 - hosts: dev
   tasks:
   - name: Checkout SCM
     git: url=https://github.com/9652040795/Hello-world.git dest=/home/user1

   - name: Maven Build
     shell: mvn clean install
     register: mvn_result

#   - name: "mvn clean task output"
#     debug:
#     var: mvn_result
