---
 - hosts: all
   tasks:
   - name: Check if file exists or not
     stat: path=/tmp/file.txt 
     register: stat_result 

   - name: view regsiter svariable
     debug: var=stat_result
     ignore_errors: yes

   - name: Create the file, if it doesnt exist already 
     file: 
       path: /tmp/file.txt 
       state: touch 
     when: stat_result.stat.exists == False
